version: "3.8"

services:
  server:
    image: "${DOCKER_CONTAINER_REGISTRY}/capstone-backend:${GITHUB_SHA}"
    container_name: capstone-backend
    environment:
      TZ: Asia/Seoul
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - capstone-backend-network
  redis:
    image: redis:6.0.9
    container_name: capstone-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - capstone-backend-network

volumes:
  redis-data:

networks:
  capstone-backend-network:
    driver: bridge